### ISSUE TITLE
Fonts are included but never used

### ISSUE THREAD

**Issue by ztamizzen** [sipmann/generator-firefoxos-app#1]
As the title says...shall I do it?

**Comment by sipmann** [comment]
for sure, feel free to remove or add them to the sample. 
But be aware that with the current dependencies version, the build is broken ;)

**Comment by ztamizzen** [comment]
Works fine as a boilerplate. :-)

Den 4 dec. 2016 8:21 em skrev "maurício sipmann" <notifications@github.com>:
